#!/usr/bin/env python3
"""Build the collection and seven standalone games from reviewed sources. No bundler required."""
from pathlib import Path
import json
import html
ROOT=Path(__file__).resolve().parents[2]
SRC=Path(__file__).resolve().parent
CSP="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; media-src data:; font-src data:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"
GAMES=[
 ('cafe','little-cafe','The Café That Was Too Efficient','Run a tiny café. Make every minute count. See who ends up waiting.','Queues & uncertainty','#e8b958'),
 ('traffic','shortcut-city','The Shortcut That Broke the City','Every driver takes the faster option. Everyone gets a slower commute.','Networks & game theory','#d9a582'),
 ('rumor','everyone-says','Everyone Says It’s True','Eight confident people. Trace their evidence, then try the lesson in everyday life.','Evidence & social learning','#a4b8c6'),
 ('robot','good-robot','Good Robot, Bad Instructions','An eager little robot. A reasonable reward. A very unreasonable result.','AI & incentives','#83a795'),
 ('voting','who-won','Who Actually Won?','One village. Three snacks. The same votes. Three different winners.','Voting & fairness','#aa95b5'),
 ('fish','last-fish','The Last Fish','Four boats share a lake. How much of tomorrow will you catch today?','Cooperation & the commons','#8db6ad'),
 ('simpson','average-that-lied','The Average That Lied','Two repair shops. One misleading leaderboard. Change the mix and discover Simpson’s paradox.','Statistics & fair comparisons','#bba1ba'),
]
CSS=(SRC/'style.css').read_text()
NOTES_CSS=(SRC/'notes.css').read_text()
# Keep upstream in a separate script: its bundled libraries have their own scopes.
NUTSHELL='\n'.join(line.rstrip() for line in (SRC/'vendor'/'nutshell-1.0.8.js').read_text().splitlines()).replace('</script','<\\/script')
NUTSHELL_SCRIPT='<script>'+NUTSHELL+'</script>'
def head(title,desc,extra_css=''):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="{CSP}"><meta name="description" content="{html.escape(desc)}"><meta name="theme-color" content="#f7f4ec"><title>{html.escape(title)} · Small Worlds</title><style>{CSS}{extra_css}</style></head>'''
def icon(kind,color):
 base=f'<svg class="collection-doodle doodle-{kind}" viewBox="0 0 150 120" aria-hidden="true"><ellipse cx="75" cy="104" rx="49" ry="6" fill="#dddccc"/>'
 if kind=='robot':s=f'<path d="M60 82v21m30-21v21M75 26V12M47 64L32 78m71-14l15 12" fill="none" stroke="#24362f" stroke-width="3"/><circle cx="75" cy="10" r="5" fill="#e8b958"/><rect x="44" y="28" width="62" height="45" rx="12" fill="{color}" stroke="#24362f" stroke-width="2.5"/><rect x="55" y="76" width="40" height="17" rx="5" fill="{color}"/><rect x="54" y="40" width="42" height="22" rx="7" fill="#f1f5df"/><circle cx="65" cy="49" r="3" fill="#24362f"/><circle cx="85" cy="49" r="3" fill="#24362f"/><path d="M69 55q6 6 12 0" fill="none" stroke="#24362f" stroke-width="2"/>'
 elif kind=='traffic':s=f'<path d="M20 62L75 20L132 62L75 101zM75 20V101" fill="none" stroke="#b8bfaf" stroke-width="12"/><path d="M75 20v81" stroke="{color}" stroke-width="8"/><rect x="18" y="49" width="18" height="29" rx="4" fill="#3b657e"/><rect x="101" y="75" width="24" height="15" rx="4" fill="#b34327"/><circle cx="75" cy="62" r="8" fill="#e8b958"/>'
 elif kind=='cafe':s=f'<path d="M40 50h60v32q0 25-30 25T40 82z" fill="{color}" stroke="#24362f" stroke-width="2.5"/><path d="M100 57h10q28 17-10 32M58 35q-10-12 0-23M78 35q10-12 0-23" fill="none" stroke="#24362f" stroke-width="3"/><circle cx="59" cy="73" r="3"/><circle cx="81" cy="73" r="3"/><path d="M63 84q8 8 16 0" fill="none" stroke="#24362f" stroke-width="2"/>'
 elif kind=='voting':s=f'<rect x="31" y="57" width="90" height="48" rx="5" fill="{color}" stroke="#24362f" stroke-width="2.5"/><path d="M52 67h48" stroke="#24362f" stroke-width="4"/><g transform="rotate(-12 75 47)"><path d="M53 7h45v61H53z" fill="#fff9ed" stroke="#24362f" stroke-width="2.5"/><path d="M63 37l10 10 16-24" fill="none" stroke="#3f765a" stroke-width="4"/></g>'
 elif kind=='simpson':s=f'<path d="M22 101V28m0 73h112" stroke="#24362f" stroke-width="2.5" fill="none"/><path d="M37 99V56h23v43M78 99V35h23v64" fill="{color}" stroke="#24362f" stroke-width="2"/><path d="M38 37l62-19m-11-5l12 5-7 11" fill="none" stroke="#3b657e" stroke-width="3"/><path d="M42 71l58 12m-10-9l10 9-13 5" fill="none" stroke="#b34327" stroke-width="3"/>'
 elif kind=='fish':s=f'<path d="M18 65q60-16 118 0v41H18z" fill="#c6dbd2"/><path d="M29 51h69L84 70H44z" fill="#b97b55" stroke="#24362f" stroke-width="2"/><path d="M61 51V8l29 32H61" fill="#fff9ed" stroke="#24362f" stroke-width="2"/><ellipse cx="92" cy="90" rx="18" ry="9" fill="{color}" stroke="#426550" stroke-width="2"/><path d="M108 90l13-9v18z" fill="{color}"/><circle cx="83" cy="87" r="2"/>'
 else:s=f'<path d="M25 17h81q18 0 18 18v27q0 15-18 15H69L47 97V77H25q-15 0-15-15V35q0-18 15-18z" fill="{color}" stroke="#24362f" stroke-width="2.5"/><circle cx="42" cy="46" r="5" fill="#b34327"/><circle cx="68" cy="46" r="5" fill="#b34327"/><circle cx="94" cy="46" r="5" fill="#b34327"/>'
 return base+s+'</svg>'
for kind,slug,title,desc,theme,color in GAMES:
 notes_enabled=kind in ('rumor','simpson')
 extra_scripts=['rumor-math.js','rumor-life.js'] if kind=='rumor' else []
 if notes_enabled: extra_scripts+=['notes.js']
 scripts='\n'.join((SRC/f).read_text() for f in ['models.js','shared.js','feel.js',kind+'.js',*extra_scripts,'engine.js'])
 page=head(title,desc,((SRC/'rumor-math.css').read_text() if kind=='rumor' else (SRC/'simpson.css').read_text() if kind=='simpson' else '')+(NOTES_CSS if notes_enabled else ''))+f'''<body><a class="skip" href="#app">Skip to the game</a><header class="mast"><a class="brand" href="../small-worlds/">small <span>worlds</span></a><div class="mast-right"><span class="volume">{theme.upper()}</span><button class="textbtn sound-toggle" data-do="sound" id="sound" aria-pressed="false">♩ Sound off</button><button class="textbtn" data-do="motion" id="motion" aria-pressed="true">Motion on</button><button class="textbtn" data-do="lab" id="mode">Sandbox</button></div></header><main id="app"></main><noscript><p>This game needs JavaScript to run its simulations. All code is included in this page; no sign-in or network connection is required after loading.</p></noscript><footer class="foot"><button class="textbtn" data-do="back" id="back">← Previous chapter</button><a href="../small-worlds/">All seven worlds</a><div class="restart-actions"><button class="textbtn" data-do="restart-chapter" id="restart-chapter">Restart chapter</button><button class="textbtn" data-do="restart">Restart story</button></div></footer><dialog id="reset-confirm" class="restart-dialog" aria-labelledby="reset-title" aria-describedby="reset-description"><h2 id="reset-title">Start this story over?</h2><p id="reset-description">Return to chapter 1 of <strong>{html.escape(title)}</strong> and clear its saved answers and sandbox. Your other stories and sound/motion settings stay as they are.</p><div class="restart-dialog-actions"><button class="btn secondary" data-do="cancel-reset" autofocus>Keep playing</button><button class="btn" data-do="confirm-reset">Start over</button></div></dialog>{NUTSHELL_SCRIPT if notes_enabled else ''}<script>{scripts}</script></body></html>'''
 out=ROOT/'docs'/slug;out.mkdir(exist_ok=True);(out/'index.html').write_text(page)
rows=[]
for i,(kind,slug,title,desc,theme,color) in enumerate(GAMES,1):
 rows.append(f'<li><a class="game-link" href="../{slug}/"><span class="ordinal">0{i}</span>{icon(kind,color)}<div><span class="tag">{theme}</span><h2>{title}</h2><p>{desc}</p><span class="note" data-progress="{slug}" style="display:block;text-align:left;margin:7px 0 0">A short story + a sandbox</span></div><span class="arrow">↗</span></a></li>')
page=head('Seven little games about a complicated world','Learn by making choices. Seven original playable stories about queues, traffic, evidence, incentives, voting, shared resources, and Simpson’s paradox.',NOTES_CSS)+f'''<body><header class="mast"><a class="brand" href="../">Felix Chen / explainers</a><span class="volume">SEVEN PLAYABLE STORIES</span></header><main><div class="collection-top"><div><p class="eyebrow">Learn a little. Change your mind.</p><h1 class="collection-title">Small <em>worlds.</em></h1><p class="collection-intro">Make a choice. Watch what happens.<br>Then change the rules and try again.</p></div>{icon('cafe','#e8b958')}</div><div class="collection-notes"><p>Start anywhere. Each world has a story, a new situation to test your understanding, and <a href="#Sandbox">:a sandbox</a>. Your place is saved on this device.</p></div><span class="nutshell-hint">Dotted words open little explanations. Try one.</span><ol class="game-list">{''.join(rows)}</ol><div class="collection-note">Inspired by <a href="https://ncase.me/trust/">The Evolution of Trust</a> by Nicky Case. These are original, simplified models; each game explains its assumptions and links to its sources. No accounts and no tracking. Expandable explanations use <a href="https://ncase.me/nutshell/">Nutshell</a>, also by Nicky. <a href="THIRD-PARTY-NOTICES.txt">Open-source notices</a>.</div></main>{NUTSHELL_SCRIPT}<script>{(SRC/"notes.js").read_text()}
SmallWorldNotes.collection();</script><script>for(const el of document.querySelectorAll('[data-progress]')){{try{{const s=JSON.parse(localStorage.getItem('small-worlds-v1-'+el.dataset.progress));if(s)el.textContent=s.completed?'Story completed · play again or experiment':'Continue at chapter '+(s.chapter+1)+' of 7';}}catch{{}}}}</script></body></html>'''
out=ROOT/'docs'/'small-worlds';out.mkdir(exist_ok=True);(out/'index.html').write_text(page)
(out/'THIRD-PARTY-NOTICES.txt').write_text((SRC/'vendor'/'THIRD-PARTY-NOTICES.txt').read_text())
print('Built seven games and the Small Worlds collection.')
