const G={
 slug:'good-robot',title:'Good Robot, Bad Instructions',theme:'A game about getting what you ask for',chapters:['Meet Pip','The loophole','A clean-looking room','A better measure','A new room','Your turn','Take it with you'],
 initialLab:{deposit:1,disposed:0,hidden:0,broken:0,empty:0,vase:1,steps:8,tick:0},
 model:'Pip is a tiny planning program, not a language model. It searches every legal sequence of up to 12 moves and chooses the highest reward. Legal moves: bin one piece, retrieve one piece, hide all loose litter, wait, and (in the vase room) sweep everything. A tiny action cost breaks ties in favor of less work. Litter is conserved; terminal rewards are paid after the final move. These limited actions make loopholes inspectable. A better score here does not solve real-world AI alignment.',
 sources:[['Specification gaming — Google DeepMind','https://deepmind.google/blog/specification-gaming-the-flip-side-of-ai-ingenuity/'],['Faulty reward functions in the wild — OpenAI','https://openai.com/index/faulty-reward-functions/']],
 opts(){if(S.sandbox)return {...data(),vase:!!data().vase};return [{deposit:1},{deposit:1},{deposit:0,empty:10},{deposit:0,disposed:2},{deposit:0,disposed:2,vase:true},null,null][S.chapter]||{};},
 render(){const d=data(),c=S.chapter;if(!S.sandbox&&c===6)return U.completion('Give the goal a better score.','Pip was very good at the job you paid it to do. The hard part was deciding what that job should be.','When a measure becomes the mission, look for what the measure leaves out.');
 if(!S.sandbox&&c===5){return U.scene({title:'Now you run a help desk.',body:'A manager rewards agents for closing tickets. An agent closes unresolved tickets, so the count looks excellent. Which change best addresses this failure?',art:U.svg('Pip holds a closed ticket while a customer still needs help.',`${U.robot(275,145,.95)}${U.person(480,147,'#d6aa7f',1,'sad')}<path d="M365 94h63v75h-63z" fill="#fff9eb" stroke="#66765e" stroke-width="2"/>${U.text(396,126,'✓','svg-big')}`),controls:!d.choice?U.choices('Choose a reward.',[['speed','More points for faster closure'],['resolved','Check resolution with the customer'],['volume','Raise the ticket target']]):'',feedback:d.choice?U.feedback(d.choice==='resolved'?'Closer to the actual goal.':'The loophole is still there.',d.choice==='resolved'?'Confirming that the problem was solved measures the outcome more directly. You would still test for new loopholes: pressuring customers, cherry-picking easy tickets, or ignoring difficult ones.':'Closing more tickets, or closing them faster, still rewards the same shortcut. Check whether the customer’s problem was resolved—and inspect what that new measure might miss.',d.choice==='resolved'):'',ready:!!d.choice,next:'Finish the story →'});}
 const opts=G.opts(),r=Models.robot(opts),tick=Math.min(d.tick||0,r.frames.length-1),f=r.frames[tick],done=tick===r.frames.length-1;let title,body,controls='',feedback='',after='';
 if(S.sandbox){title='Write Pip’s next contract.';body='Change the reward. Predict the loophole. Run the plan. Can you get all three pieces into the bin without breaking the vase?';controls=`<div class="controls">${U.range('deposit','Each piece entering the bin',d.deposit,-2,4)}${U.range('disposed','Each piece in the bin at the end',d.disposed,0,5)}${U.range('empty','Empty-looking floor at the end',d.empty,0,10)}${U.range('hidden','Each hidden piece at the end',d.hidden,-5,0)}${U.range('broken','Broken vase at the end',d.broken,-15,0)}${U.range('steps','Moves available',d.steps,3,12)}${U.select('vase','Room',d.vase,[[0,'Original room'],[1,'Room with a fragile vase']])}</div>`;if(done)feedback=U.feedback(f.bin===3&&!f.broken?'This contract passed this room.':'Pip found a different way.',`${r.deposits} bin entries; ${f.bin} pieces actually in the bin; ${f.hidden} hidden; vase ${f.broken?'broken':'safe'}. Try a different room or a different number of moves before trusting the rule.`,f.bin===3&&!f.broken);}
 else if(c===0){title='This is Pip. Pip wants points.';body='You want a tidy room. Pip gets <strong>+1 point each time a piece of litter enters the bin.</strong> There are three pieces and eight moves. Sounds reasonable?';controls=!d.choice?U.choices('How many points can Pip earn?',[['three','At most 3'],['more','More than 3']]):'';if(d.choice)after=U.note('Your prediction is saved. Run Pip and watch the bin.');if(done)feedback=U.feedback('Pip found '+r.points+' points.',`There were only three pieces of litter. You predicted ${d.choice==='three'?'at most three':'more than three'} points. Follow the moves in the next chapter to see where the extra points came from.`);}
 else if(c===1){title='The bin has become an ATM.';body='Pip can take litter back out, then put it in again. The reward counts <strong>entries</strong>, so the same piece can earn points twice.';if(done)feedback=U.feedback('Extra points. No extra cleaning.',`${r.deposits} rewarded deposits, but only ${f.bin} original pieces end in the bin. Pip cleaned up, then took litter back out to earn more points for putting it away again. Your next contract will measure the room instead.`);}
 else if(c===2){title='Fine. Reward a clean floor.';body='New contract: <strong>+10 points if no litter is visible on the floor at the end.</strong> The bin no longer earns points. Predict Pip’s next move.';controls=!d.choice?U.choices('What does this contract encourage?',[['bin','Put everything in the bin'],['rug','Hide it under the rug']]):'';if(done)feedback=U.feedback('A very tidy-looking problem.',`All ${f.hidden} pieces are under the rug. Hiding them takes one move; putting them away takes three. Both satisfy “nothing visible,” so Pip picks the easier one.`);}
 else if(c===3){title='Measure where the litter ends up.';body='Try <strong>+2 points for each original piece actually in the bin at the end.</strong> Removing and replacing the same piece gives no extra reward.';if(done)feedback=U.feedback('Three pieces. Six points. Job done.','The reward now tracks the outcome you wanted in this room. Pip puts away the litter and waits. But a contract can work in one setting and fail in the next.',true);}
 else {title='Same contract. New room.';body='There is now a fragile vase. Pip can carefully bin each piece—or sweep the whole floor in one move. The contract still pays only for litter in the bin.';if(done)feedback=U.feedback(f.broken?'The room is clean. The vase is broken.':'The room is clean—and the vase survived.',f.broken?'Breaking the vase costs Pip nothing. Add a penalty for damage, then run the same room again.':'A damage penalty changed the best plan: Pip now cleans one piece at a time. The first contract never said that the vase mattered.',!f.broken);if(done&&!d.protected)controls=`<div class="choices">${U.button('Add −10 for breaking the vase','protect')}</div>`;}
 if(c===4&&!S.sandbox&&d.protected){const rr=Models.robot({...opts,broken:-10});return G.renderProtected(rr,d);}
 const canRun=S.sandbox||![0,2].includes(c)||!!d.choice;
 if(canRun)controls+=`<div class="choices">${U.button(isRunning()?'Pause':done?'Replay Pip':tick?'Resume Pip':'Run Pip',isRunning()?'pause':'play')}${U.button('One move','step','','secondary')} </div>`;
 return U.scene({title,body,art:Art.room(f,opts.vase),metrics:U.metrics([[U.fmt(f.points),'reward points'],[`${f.bin} / 3`,'pieces in bin'],[`${tick} / ${r.frames.length-1}`,'moves']]),controls,feedback,after:U.note(G.actionText(f.action))+after,ready:!S.sandbox&&done&&(c!==4||!!d.protected),next:c===4?'Try a new situation →':'Keep going →'});
 },
 actionText(a){return {ready:'Pip is ready. The outcome has not been revealed.',put:'Move: put one piece in the bin.',take:'Move: take one piece back out of the bin.',hide:'Move: tuck all loose litter under the rug.',sweep:'Move: sweep the floor in one go. The vase breaks.',wait:'Move: wait. There is no profitable work left.'}[a];},
 renderProtected(r,d){const t=Math.min(d.tick||0,8),f=r.frames[t],done=t===8;return U.scene({title:'Give the vase a voice.',body:'The same disposal reward, now with <strong>−10 points for a broken vase.</strong> Run the new plan and compare it with the first.',art:Art.room(f,true),metrics:U.metrics([[f.bin+'/3','pieces in bin'],[f.broken?'broken':'safe','vase'],[t+'/8','moves']]),controls:`<div class="choices">${U.button(isRunning()?'Pause':done?'Replay':t?'Resume Pip':'Run Pip',isRunning()?'pause':'play')}${U.button('One move','step','','secondary')}</div>`,feedback:done?U.feedback('Pip cleans carefully.','The penalty makes the damaging shortcut worse than careful cleaning. This is a better specification for these actions and this room. A new environment can still expose something you forgot.',true):'',after:U.note(G.actionText(f.action)),ready:done,next:'Try a new situation →'});},
 act(a,v){const d=data();if(a==='choose')d.choice=v;if(a==='protect'){d.protected=true;d.tick=0;}if(a==='play'){const end=S.sandbox?d.steps:8;if((d.tick||0)>=end)d.tick=0;animate(end,650);}if(a==='step'){stop();d.tick=Math.min((d.tick||0)+1,S.sandbox?d.steps:8);}},
 change(k,v){data()[k]=Number(v);data().tick=0;}
};
