/* Invented everyday situations: applications of the model, not historical claims. */
const RumorLife={
 cases:{
  news:{label:'A repeated headline',title:'Five articles. One original claim.',body:'Five sites say a new battery lasts twice as long. Each article sounds confident. You are about to share the news.',quotes:['“Twice as long!”','“A breakthrough.”','“Everyone says so.”'],people:['Site A','Site B','Site C'],question:'What is the most useful next step?',options:[['count','Treat five articles as five confirmations'],['trace','Find the original test and who checked it'],['reject','Assume a popular claim must be false']],correct:'trace',result:'Trace the claim before multiplying your confidence.',explanation:'Five articles may all quote one press release. That is one source repeated, not five independent tests. Find the original measurements, their conditions, and any independent replication. The claim could still be true.',pitfall:'Mistaking the number of links for the number of observations.',habit:'Before sharing: open the original source, check what was measured, and say what remains unverified.',sentence:'“These articles cite the same test. Has anyone independently reproduced it?”'},
  shopping:{label:'A product recommendation',title:'Your friends agree. Did they try it?',body:'Several friends recommend a camera. They all watched the same review; none has used it in low light, which matters most to you.',quotes:['“Great camera.”','“I saw that review.”','“Me too!”'],people:['A friend','Another friend','You'],question:'What would add the most useful evidence?',options:[['more','Ask more people who watched that review'],['test','Look for relevant first-hand tests or try it'],['opposite','Buy the other camera to avoid the herd']],correct:'test',result:'Look for a new observation that answers your question.',explanation:'A first-hand low-light test can add evidence the repeated recommendation lacks. Check that the tester’s needs and conditions match yours. Independence helps, but an irrelevant or unreliable test is still weak evidence.',pitfall:'Treating borrowed confidence as personal experience—or copying someone else’s priorities.',habit:'Ask “Did you use it yourself, and under what conditions?” Separate their observation from their recommendation.',sentence:'“What did you personally try? I care about indoor photos, not daytime video.”'},
  meeting:{label:'A team meeting',title:'The leader speaks. Everyone nods.',body:'A team is deciding whether a release will be ready on Tuesday. The lead says yes first. Everyone else hears that before giving an estimate.',quotes:['“Tuesday is fine.”','“Sounds right.”','“I agree.”'],people:['Team lead','A teammate','Another teammate'],question:'How would you improve the next discussion?',options:[['leader','Have the most senior person explain first'],['private','Write estimates and evidence before discussion'],['vote','Keep voting until everyone agrees']],correct:'private',result:'Collect independent starting points, then discuss the reasons.',explanation:'Ask everyone to write an estimate, a concrete observation, and an uncertainty before seeing others’ answers. Reveal them together, investigate differences, and update. Do not merely average every opinion: expertise and evidence quality matter.',pitfall:'Losing a person’s private concern inside their public agreement.',habit:'As a leader, give others space to report evidence before you anchor the room. As a teammate, share the observation even if your final recommendation agrees.',sentence:'“I also lean Tuesday, but two tests still fail. Here is what would change my estimate.”'}
 },
 render(d){
  const key=d.lifeCase||'news',q=this.cases[key],answer=d.lifeAnswers?.[key],count=Object.keys(d.lifeAnswers||{}).length;
  const people=q.people.map((name,i)=>{const x=140+i*220;return `<path d="M${x-90} 20h180v46h-61l-14 15V66h-105z" fill="#f8f6ee" stroke="#a4b4a3" stroke-width="1.5"/>${U.text(x,48,q.quotes[i],'svg-small')}${U.person(x,111,['#d8aa88','#92b2a8','#b09bb5'][i],.74,'hmm',{id:'everyday-'+i})}${U.text(x,212,name,'svg-small')}`}).join('');
  const art=`<div class="life-tabs" role="group" aria-label="Everyday situations">${Object.entries(this.cases).map(([k,v])=>U.button((d.lifeAnswers?.[k]?'✓ ':'')+v.label,'life-case',k,k===key?'selected':'secondary')).join('')}</div><div class="life-scene"><h2>${q.title}</h2><p>${q.body}</p>${U.svg(q.people.map((p,i)=>p+' says '+q.quotes[i]).join('. '),people,235)}</div>`;
  const controls=!answer?U.choices(q.question,q.options,'life-answer'):`<div class="choices">${U.button('Try this situation again','life-retry','','secondary')}</div>`;
  const feedback=answer?U.feedback(q.result,q.explanation,answer===q.correct):'';
  const application=answer?`<div class="life-application"><p><span class="life-label">THE PITFALL</span>${q.pitfall}</p><p><span class="life-label">A BETTER HABIT</span>${q.habit}</p><blockquote>${q.sentence}</blockquote></div>`:'';
  const takeaway=`<div class="life-principles"><h2>How to behave when everyone agrees.</h2><ol><li><strong>Bring your evidence, even when you agree.</strong> “I saw X” gives the group more than another “yes.”</li><li><strong>Count origins and weigh quality.</strong> Ten repetitions of one observation are not ten tests. Independent expert work deserves weight.</li><li><strong>Make room to update.</strong> Name what would change your mind. Revise your view when better evidence arrives.</li></ol><p>Neither agreement nor disagreement is a guarantee. The aim is a well-supported belief, not automatic conformity or automatic contrarianism.</p><p class="note">These are illustrative applications. Real sources have unequal expertise, partial overlap, and uncertain reliability; the game’s exact percentages do not transfer to them.</p></div>`;
  return U.scene({eyebrow:'Take the lesson into your day',title:'Ask what they saw. Share what you saw.',body:'The crowd was made of reasonable people. Better conversations make their evidence visible. Try these three everyday situations.',art,controls,feedback,after:application+`<p class="life-progress">${count} of 3 situations explored</p>`+takeaway+`<div class="choices">${U.button('Open the sandbox','lab')}<a class="btn secondary" href="../small-worlds/">Choose another world →</a></div>`});
 },
 act(a,v,d){if(a==='life-case')d.lifeCase=v;if(a==='life-answer')(d.lifeAnswers||={})[d.lifeCase||'news']=v;if(a==='life-retry')delete (d.lifeAnswers||={})[d.lifeCase||'news'];}
};
