const G={slug:'shortcut-city',title:'The Shortcut That Broke the City',theme:'A game about individually sensible decisions',chapters:['Morning commute','Build a shortcut','The new normal','A city planner','A quieter city','Your turn','Take it with you'],initialLab:{n:4000,cost:0,shortcut:1,mode:'self',share:0},model:'A continuous-flow, one-way traffic network. The two narrow roads take one minute per 100 drivers; the two broad roads always take 45 minutes. Everyone has the same home and workplace, knows route times, and chooses a fastest route. We solve the equilibrium directly; animated dots illustrate the computed flow. Fixed demand means this is Braess’s paradox, not induced demand. Real road networks add junctions, travel-time uncertainty, multiple destinations, and changing demand.',sources:[['The prevalence of Braess’ paradox — Steinberg & Zangwill','https://pubsonline.informs.org/doi/10.1287/trsc.17.3.301'],['Experiments on road networks — Morgan, Orzen & Sefton','https://faculty.haas.berkeley.edu/rjmorgan/traffic.pdf']],
 render(){const d=data(),c=S.chapter;if(!S.sandbox&&c===6)return U.completion('A faster choice can make a slower city.','The shortcut really was the faster choice for each driver, holding everyone else’s routes fixed. As everyone took that option, they crowded the same roads and made the whole commute slower.','Compare your best move now with the outcome after everyone makes their best move.');
 if(!S.sandbox&&c===5)return U.scene({title:'A shortcut in a computer network.',body:'Two shared servers are busy. You add a fast connection between them. Every app independently chooses whichever route currently looks quickest.',art:Art.traffic(Models.traffic(),true),controls:!d.choice?U.choices('What can you safely conclude?',[['always','Adding a connection must help'],['never','Extra connections always hurt'],['depends','Check the new routing equilibrium']]):'',feedback:d.choice?U.feedback(d.choice==='depends'?'Look at the system after it adapts.':'The road count isn’t enough.',d.choice==='depends'?'The connection might help, hurt, or go unused. It depends on demand, congestion, and routing behavior. Compare the resulting loads—not just the speed of the new link.':'At low demand, our shortcut helped. At high demand, it hurt. A new connection changes choices as well as capacity, so you need to evaluate the resulting flow.',d.choice==='depends'):'',ready:!!d.choice,next:'Finish the story →'});
 let opts={n:4000,shortcut:c>=2},title,body,controls='',feedback='',after='';
 if(S.sandbox){opts={n:d.n,cost:d.cost,shortcut:!!d.shortcut,share:d.mode==='planned'?d.share/100:null};title='Plan a different rush hour.';body='Try to make the shortcut help. Change demand, the shortcut’s travel time, or who controls the routes.';controls=`<div class="controls">${U.range('n','Drivers',d.n,1000,10000,500)}${U.range('cost','Shortcut travel time',d.cost,0,40,1,' min')}${U.select('shortcut','Shortcut',d.shortcut,[[1,'Open'],[0,'Closed']])}${U.select('mode','Routing',d.mode,[['self','Drivers choose independently'],['planned','You allocate the traffic']])}${d.mode==='planned'?U.range('share','Drivers using the shortcut',d.share,0,100,1,'%'):''}</div>`;}
 else if(c===0){title='Get 4,000 people to work.';body='There are two routes. Each has one broad road that takes <strong>45 minutes</strong> and one narrow road that slows down as more drivers use it. With 2,000 drivers per route, the narrow part takes 20 minutes.';opts.shortcut=false;controls=U.choices('Your trip is 65 minutes. Which route would you pick?',[['top','The upper route'],['bottom','The lower route']]);if(d.choice)feedback=U.feedback('Either route takes 65 minutes.','The routes balance: if too many people switch to one, its narrow road slows down. No driver can save time by switching alone.',true);}
 else if(c===1){title='A free shortcut. What could go wrong?';body='Connect the upper junction to the lower one with a <strong>zero-minute, one-way shortcut.</strong> It lets drivers use both narrow roads and avoid the 45-minute roads.';opts.shortcut=!!d.choice;controls=!d.choice?U.choices('Predict the new average trip.',[['faster','Faster than 65 minutes'],['same','Still 65 minutes'],['slower','Slower than 65 minutes']]):'';if(d.choice)feedback=U.feedback('80 minutes. For everyone.',`You predicted ${d.choice==='faster'?'a faster trip':d.choice==='same'?'no change':'a slower trip'}. All 4,000 drivers now use both narrow roads: 40 + 0 + 40 = 80. We added a road without adding a single driver.`);}
 else if(c===2){
  opts.share=(d.adoption??4000)/4000;title='The shortcut really is better for you.';
  body=d.choice?'Use the rewind controls below to compare your options as the city adapts. Hold the other drivers’ choices fixed: which route is faster for you at that moment?':'After everyone adapts, the shortcut takes <strong>80 minutes</strong>. Hold the other drivers’ choices fixed. Would switching to an outer route help <em>you</em>? Compare the alternatives available now—not the old 65-minute world.';
  controls=!d.choice?U.choices('What would your outer-route trip take?', [['65','65 minutes'],['85','85 minutes']]):'';
  if(d.choice){const snapshot=Models.traffic(opts),gain=snapshot.outer-snapshot.cross;feedback=U.feedback(`${U.fmt(snapshot.load/100)} + 45 = ${U.fmt(snapshot.outer)} minutes.`,(d.adoption??4000)===4000?'The narrow road still carries almost all the other drivers. Taking the shortcut saves you 5 minutes compared with your current alternative. Nobody can improve by switching alone, yet everyone was better off before the road opened.':`In this snapshot, the shortcut takes ${U.fmt(snapshot.cross)} minutes and saves you ${U.fmt(gain)} minutes. That individual advantage encourages more drivers to switch, which crowds the roads shared with everyone else.`,d.choice==='85');}
 }
 else if(c===3){title='You’re in charge. Fix the city.';body='Try closing the shortcut. Or coordinate the drivers, so they don’t all chase the same tempting route.';const mode=d.mode||'self';opts.shortcut=mode!=='closed';opts.share=mode==='planned'?(d.share||0)/100:null;controls=`<div class="choices">${[['self','Let drivers choose'],['closed','Close the shortcut'],['planned','Coordinate the routes']].map(([v,t])=>U.button(t,'mode',v,mode===v?'selected':'secondary')).join('')}</div>${mode==='planned'?`<div class="controls">${U.range('share','Share using the shortcut',d.share||0,0,100,1,'%')}</div>`:''}`;if(mode!=='self')feedback=U.feedback(mode==='closed'?'A missing road, a better commute.':'A shared plan changes the outcome.',mode==='closed'?'The old balance returns: 2,000 per route, 65 minutes each. Closing the road changes everyone’s options at once.':'Keep the shortcut share near 12–13%. That gives an average of about 64.7 minutes. But drivers assigned an outer route could save time by switching onto the shortcut. Coordination needs something that makes it stick.',true);}
 else {title='Try Sunday morning.';body='The very same network now has only <strong>2,000 drivers</strong>. Predict what happens when the shortcut opens.';opts={n:2000,shortcut:!!d.choice};controls=!d.choice?U.choices('This time, does the shortcut help?',[['helps','It helps'],['hurts','It still hurts']]):'';if(d.choice)feedback=U.feedback('40 minutes instead of 55.','With light traffic, the two narrow roads take just 20 minutes each. The shortcut helps. “More roads are bad” would be the wrong lesson; the interaction between demand and incentives is what matters.',true);}
 const r=Models.traffic(opts);r.cost=opts.cost||0;
 if(S.sandbox)feedback=U.feedback(`${U.fmt(r.mean)} minutes ${r.mean<r.baseline?'— faster':r.mean>r.baseline?'— slower':'— unchanged'}.`,`Without the shortcut, this demand would give ${U.fmt(r.baseline)} minutes. ${U.fmt(r.x,0)} drivers use the shortcut. ${d.mode==='planned'?'These are assigned routes, not necessarily choices drivers would stick to on their own.':'At this equilibrium, no driver can gain by switching routes alone.'}`,r.mean<=r.baseline);
 after=U.note('Narrow-road time = drivers on that road ÷ 100. Broad-road time = 45 minutes.');
 if(!S.sandbox&&c===2&&d.choice){
  const adoption=d.adoption??4000,saving=r.outer-r.cross;
  after=`<section class="driver-experiment"><h2>Rewind. Would you take the shortcut?</h2><p>Freeze everyone else’s routes at any point. The two trip times below are <strong>your alternatives under the same traffic conditions</strong>.</p><div class="choices">${U.button('When it first opens','adoption',0,adoption===0?'selected':'secondary')}${U.button('After everyone adapts','adoption',4000,adoption===4000?'selected':'secondary')}</div><div class="controls">${U.range('adoption','Drivers who have adopted the shortcut',adoption,0,4000,500)}</div><div class="driver-options"><div><span>Your outer route</span><strong>${U.fmt(r.load/100)} + 45 = ${U.fmt(r.outer)} min</strong></div><div class="better"><span>Your shortcut route</span><strong>${U.fmt(r.load/100)} + 0 + ${U.fmt(r.load/100)} = ${U.fmt(r.cross)} min</strong></div></div><p class="driver-gain" role="status">Choosing the shortcut saves you <strong>${U.fmt(saving)} minutes</strong> at this moment.</p><p>${adoption===0?'At first you can take 40 minutes instead of 65. As other drivers make the same sensible choice, both narrow roads fill up.':adoption===4000?'Now you can take 80 minutes instead of 85. The shortcut still helps you individually—even though everyone used to get to work in 65 minutes.':'Every switch adds traffic to a narrow road used by others. Your personal gain and the delay you impose on other drivers are different quantities.'}</p><p class="note">This is a continuous-flow model: one driver has negligible effect on road times. The chart above shows the current allocation; intermediate allocations are not equilibria.</p></section>`+after;
 }

 return U.scene({title,body,art:Art.traffic(r,opts.shortcut),metrics:U.metrics([[U.fmt(r.mean)+' min','average trip',r.mean>r.baseline],[U.fmt(r.x,0),'use the shortcut'],[U.fmt(r.side,0),'on each outer route']]),controls,feedback,after,ready:!S.sandbox&&(c===3?d.mode&&d.mode!=='self':!!d.choice)});
 },act(a,v){const d=data();if(a==='choose')d.choice=v;if(a==='mode')d.mode=v;if(a==='adoption')d.adoption=Number(v);},change(k,v){data()[k]=k==='mode'?v:Number(v);}
};
