const G={slug:'shortcut-city',title:'The Shortcut That Broke the City',theme:'A game about individually sensible decisions',chapters:['Morning commute','Build a shortcut','The new normal','A city planner','A quieter city','Your turn','Take it with you'],initialLab:{n:4000,cost:0,shortcut:1,mode:'self',share:0},model:'A continuous-flow, one-way traffic network. The two narrow roads take one minute per 100 drivers; the two broad roads always take 45 minutes. Everyone has the same home and workplace, knows route times, and chooses a fastest route. We solve the equilibrium directly; animated dots illustrate the computed flow. Fixed demand means this is Braess’s paradox, not induced demand. Real road networks add junctions, travel-time uncertainty, multiple destinations, and changing demand.',sources:[['The prevalence of Braess’ paradox — Steinberg & Zangwill','https://pubsonline.informs.org/doi/10.1287/trsc.17.3.301'],['Experiments on road networks — Morgan, Orzen & Sefton','https://faculty.haas.berkeley.edu/rjmorgan/traffic.pdf']],
 render(){const d=data(),c=S.chapter;if(!S.sandbox&&c===6)return U.completion('A faster choice can make a slower city.','The new road changed everyone’s incentives. The trouble emerged from the way routes interacted.','Ask what everyone will do after the rules change.');
 if(!S.sandbox&&c===5)return U.scene({title:'A shortcut in a computer network.',body:'Two shared servers are busy. You add a fast connection between them. Every app independently chooses whichever route currently looks quickest.',art:Art.traffic(Models.traffic(),true),controls:!d.choice?U.choices('What can you safely conclude?',[['always','Adding a connection must help'],['never','Extra connections always hurt'],['depends','Check the new routing equilibrium']]):'',feedback:d.choice?U.feedback(d.choice==='depends'?'Look at the system after it adapts.':'The road count isn’t enough.',d.choice==='depends'?'The connection might help, hurt, or go unused. It depends on demand, congestion, and routing behavior. Compare the resulting loads—not just the speed of the new link.':'At low demand, our shortcut helped. At high demand, it hurt. A new connection changes choices as well as capacity, so you need to evaluate the resulting flow.',d.choice==='depends'):'',ready:!!d.choice,next:'Finish the story →'});
 let opts={n:4000,shortcut:c>=2},title,body,controls='',feedback='',after='';
 if(S.sandbox){opts={n:d.n,cost:d.cost,shortcut:!!d.shortcut,share:d.mode==='planned'?d.share/100:null};title='Plan a different rush hour.';body='Try to make the shortcut help. Change demand, the shortcut’s travel time, or who controls the routes.';controls=`<div class="controls">${U.range('n','Drivers',d.n,1000,10000,500)}${U.range('cost','Shortcut travel time',d.cost,0,40,1,' min')}${U.select('shortcut','Shortcut',d.shortcut,[[1,'Open'],[0,'Closed']])}${U.select('mode','Routing',d.mode,[['self','Drivers choose independently'],['planned','You allocate the traffic']])}${d.mode==='planned'?U.range('share','Drivers using the shortcut',d.share,0,100,1,'%'):''}</div>`;}
 else if(c===0){title='Get 4,000 people to work.';body='There are two routes. Each has one broad road that takes <strong>45 minutes</strong> and one narrow road that slows down as more drivers use it. With 2,000 drivers per route, the narrow part takes 20 minutes.';opts.shortcut=false;controls=U.choices('Your trip is 65 minutes. Which route would you pick?',[['top','The upper route'],['bottom','The lower route']]);if(d.choice)feedback=U.feedback('Either route takes 65 minutes.','The routes balance: if too many people switch to one, its narrow road slows down. No driver can save time by switching alone.',true);}
 else if(c===1){title='A free shortcut. What could go wrong?';body='Connect the upper junction to the lower one with a <strong>zero-minute, one-way shortcut.</strong> It lets drivers use both narrow roads and avoid the 45-minute roads.';opts.shortcut=!!d.choice;controls=!d.choice?U.choices('Predict the new average trip.',[['faster','Faster than 65 minutes'],['same','Still 65 minutes'],['slower','Slower than 65 minutes']]):'';if(d.choice)feedback=U.feedback('80 minutes. For everyone.',`You predicted ${d.choice==='faster'?'a faster trip':d.choice==='same'?'no change':'a slower trip'}. All 4,000 drivers now use both narrow roads: 40 + 0 + 40 = 80. We added a road without adding a single driver.`);}
 else if(c===2){title='Why doesn’t somebody switch back?';body='Everyone takes the shortcut: <strong>40 + 0 + 40 = 80 minutes.</strong> You could return to an outer route, while everyone else keeps doing what they are doing.';controls=!d.choice?U.choices('What would your outer-route trip take?',[['65','65 minutes'],['85','85 minutes']]):'';if(d.choice)feedback=U.feedback('40 + 45 = 85 minutes.',`The narrow road still carries almost all the other drivers. Switching alone would make your trip worse. This is an equilibrium: nobody can improve by changing their own route, yet everyone was better off before.`);}
 else if(c===3){title='You’re in charge. Fix the city.';body='Try closing the shortcut. Or coordinate the drivers, so they don’t all chase the same tempting route.';const mode=d.mode||'self';opts.shortcut=mode!=='closed';opts.share=mode==='planned'?(d.share||0)/100:null;controls=`<div class="choices">${[['self','Let drivers choose'],['closed','Close the shortcut'],['planned','Coordinate the routes']].map(([v,t])=>U.button(t,'mode',v,mode===v?'selected':'secondary')).join('')}</div>${mode==='planned'?`<div class="controls">${U.range('share','Share using the shortcut',d.share||0,0,100,1,'%')}</div>`:''}`;if(mode!=='self')feedback=U.feedback(mode==='closed'?'A missing road, a better commute.':'A shared plan changes the outcome.',mode==='closed'?'The old balance returns: 2,000 per route, 65 minutes each. Closing the road changes everyone’s options at once.':'Keep the shortcut share near 12–13%. That gives an average of about 64.7 minutes. But shortcut users have an incentive to deviate from a plan: coordination needs something that makes it stick.',true);}
 else {title='Try Sunday morning.';body='The very same network now has only <strong>2,000 drivers</strong>. Predict what happens when the shortcut opens.';opts={n:2000,shortcut:!!d.choice};controls=!d.choice?U.choices('This time, does the shortcut help?',[['helps','It helps'],['hurts','It still hurts']]):'';if(d.choice)feedback=U.feedback('40 minutes instead of 55.','With light traffic, the two narrow roads take just 20 minutes each. The shortcut helps. “More roads are bad” would be the wrong lesson; the interaction between demand and incentives is what matters.',true);}
 const r=Models.traffic(opts);r.cost=opts.cost||0;
 if(S.sandbox)feedback=U.feedback(`${U.fmt(r.mean)} minutes ${r.mean<r.baseline?'— faster':r.mean>r.baseline?'— slower':'— unchanged'}.`,`Without the shortcut, this demand would give ${U.fmt(r.baseline)} minutes. ${U.fmt(r.x,0)} drivers use the shortcut. ${d.mode==='planned'?'These are assigned routes, not necessarily choices drivers would stick to on their own.':'At this equilibrium, no driver can gain by switching routes alone.'}`,r.mean<=r.baseline);
 after=U.note('Narrow-road time = drivers on that road ÷ 100. Broad-road time = 45 minutes.');
 return U.scene({title,body,art:Art.traffic(r,opts.shortcut),metrics:U.metrics([[U.fmt(r.mean)+' min','average trip',r.mean>r.baseline],[U.fmt(r.x,0),'use the shortcut'],[U.fmt(r.side,0),'on each outer route']]),controls,feedback,after,ready:!S.sandbox&&(c===3?d.mode&&d.mode!=='self':!!d.choice)});
 },act(a,v){const d=data();if(a==='choose')d.choice=v;if(a==='mode')d.mode=v;},change(k,v){data()[k]=k==='mode'?v:Number(v);}
};
